apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: klant1
  labels:
    component: database
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi