apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin
  namespace: klant1
  labels:
    component: phpmyadmin
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi