apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver
  namespace: klant1
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/klant1"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver
  namespace: klant1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi